---
- name: Ensure netplan directory exists
  file:
    path: /etc/netplan
    state: directory

- name: Get the public interface name
  shell: "ip route | grep default | awk '{print $5}'"
  register: public_interface
  changed_when: false

- name: Debug the interface name
  debug:
    msg: "Public interface detected: {{ public_interface.stdout }}"

- name: Create netplan configuration for VLAN 199 on the public interface
  template:
    src: 51-k8s-vip-vlans.yaml.j2
    dest: /etc/netplan/51-k8s-vip-vlans.yaml
    mode: '0640'
  vars:
    interface_name: "{{ public_interface.stdout }}"

- name: Apply netplan configuration
  command: netplan apply