
- name: Get system hostname 
  shell: "hostname -s"
  register: node_name
  changed_when: false

- name: Set system hostname
  set_fact:
    k8s_name: "{{ node_name.stdout }}"
  changed_when: false

- name: Add All Labels to node
  shell: "kubectl label node --kubeconfig /etc/kubernetes/admin.conf --overwrite {{ k8s_name }} {{ item }}"
  changed_when: false
  loop: "{{ kubernetes_labels }}"