---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    reload: yes

- name: Set fs.inotify.max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    state: present
    reload: yes

- name: Set fs.inotify.max_user_instances
  sysctl:
    name: fs.inotify.max_user_instances
    value: '512'
    state: present
    reload: yes

- name: Disable swap
  command: swapoff -a
  become: true

- name: Remove swap entries from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
  become: true