---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: '4.11.x'
  interval: 30m
  targetNamespace: ingress-nginx
  install:
    createNamespace: true
  valuesFrom:
    - kind: ConfigMap
      name: global-config
      valuesKey: replicas
      targetPath: controller.replicaCount
  values:
    controller:
      kind: Deployment
      service:
        type: LoadBalancer
      admissionWebhooks:
        enabled: false
      metrics:
        enabled: false
