---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ansible-semaphore
  namespace: flux-system
spec:
  interval: 60m
  url: oci://ghcr.io/cloudhippie/charts/ansible-semaphore
  ref:
    semver: 10.0.x