---
# tasks/main.yml

- name: Update the apt package index
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  register: upgrade_result

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Add server to the reboot required list
  set_fact:
    reboot_required_servers: "{{ reboot_required_servers | default([]) + [inventory_hostname] }}"
  when: reboot_required.stat.exists

- name: Print list of servers that need a reboot
  debug:
    msg: "The following servers require a reboot: {{ reboot_required_servers }}"
  when: reboot_required_servers is defined

