---
- name: Update the apt package index
  apt:
    update_cache: yes

- name: Upgrade all installed packages (Debian-based)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install yum-utils for needs-restarting check
  yum:
    name: yum-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Check if a reboot is required (RedHat-based)
  shell: needs-restarting -r || echo "reboot not needed"
  register: needs_restarting
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Set reboot required flag (RedHat-based)
  set_fact:
    reboot_required: true
  when: 
    - ansible_os_family == "RedHat"
    - needs_restarting.stdout.find("reboot not needed") == -1

- name: Check if the system requires a reboot (Debian-based)
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_os_family == "Debian"

- name: Set reboot required flag (Debian-based)
  set_fact:
    reboot_required: true
  when: reboot_required_file.stat.exists

# - name: Reboot the system if needed
#   reboot:
#   when: reboot_required is defined and reboot_required
