---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      version: '1.15.x'
  interval: 60m
  targetNamespace: rook-ceph
  install:
    createNamespace: true
