---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: '3.12.x'
  interval: 60m
  targetNamespace: metrics-server
  install:
    createNamespace: true
  valuesFrom:
    - kind: ConfigMap
      name: global-config
      valuesKey: replicas
      targetPath: replicas
  values:
    podLabels:
      app: metrics-server
    args:
      - --kubelet-insecure-tls
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - metrics-server
          topologyKey: kubernetes.io/hostname