---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "v1.15.x"
  interval: 15m
  targetNamespace: cert-manager
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
    replicaCount: 1 # <--- TODO Change this value to 3
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - cert-manager
            topologyKey: kubernetes.io/hostname
    strategy:
      type: Recreate
    webhook:
      replicaCount: 1 # <--- TODO Change this value to 3
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - webhook
              topologyKey: kubernetes.io/hostname
      strategy:
        type: Recreate
    cainjector:
      replicaCount: 1 # <--- TODO Change this value to 3
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - cainjector
              topologyKey: kubernetes.io/hostname
      strategy:
        type: Recreate
