
# vars:
#   - name: REPLICA_COUNT
#     objref:
#       kind: ConfigMap
#       name: my-config
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.REPLICA_COUNT
# Flux installed resources
resources:
  - metrics-server
  - metallb
  - cert-manager
  - ingress-nginx
  - headlamp
  - rook-ceph

# TODO 
# create a global configmap that s kinda like a helm values yaml that all of the helmrealeases can use in their templates
# so it would define the number of replicas and in each helmrelease i