---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: global-config
    namespace: flux-system
    literals:
      - replicas=1

# Flux installed resources
resources:
  - metrics-server
  - metallb
  - cert-manager
  - ingress-nginx
  - headlamp
  - rook-ceph
  - capacitor
  - semaphore
# so it would define the number of replicas and in each helmrelease
# then we can use the vars in the kustomization.yaml to set the number of replicas in the helmreleases
generatorOptions:
  disableNameSuffixHash: true