---

- hosts: all
  become: yes
  roles:
    - system_upgrade

- hosts: all
  become: yes
  vars:
    k8s_version: "v1.31"
    containerd_version: "latest"
    nerdctl_version: "latest"
    runc_version: "latest"
    cni_version: "latest"
    crictl_version: "latest"
  roles:
    - sysctl
    - install_containerd
    - install_k8s

- hosts: cp-leader
  become: yes
  roles:
    - bootstrap_k8s
    - control_plane_info

- name: Join Server nodes to the Kubernetes cluster
  hosts: cp-follower
  become: yes
  gather_facts: no
  vars:
    kubeadm_extra: "--control-plane"
  roles:
    - join_node

- name: Join worker nodes to the Kubernetes cluster
  hosts: workers
  become: yes
  gather_facts: no
  vars:
    kubeadm_extra: ""
  roles:
    - join_node

- name: Configure the Kubernetes VIP interface
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - k8s_vip_interface
