---

- hosts: cp-leader
  become: yes
  roles:
    - bootstrap_k8s

- name: Join Server nodes to the Kubernetes cluster
  hosts: cp-follower
  become: yes
  gather_facts: no
  roles:
    - join-cp

# - name: Join worker nodes to the Kubernetes cluster
#   hosts: workers
#   become: yes
#   gather_facts: no
#   vars:
#     kubeadm_extra: ""
#   roles:
#     - join_node


