# all nodes should have k8s installed on them
- name: Add worker Label to nodes
  hosts: raspberry-pi
  become: yes
  vars:
    kubernetes_labels:
      - node-role.kubernetes.io/worker=''
  gather_facts: no
  roles:
    - label-nodes

- name: Remove control-plane NoSchedule taint from nodes
  hosts: raspberry-pi
  become: yes
  vars:
    kubernetes_taints:
      - node-role.kubernetes.io/control-plane:NoSchedule-
  gather_facts: no
  roles:
    - taint-nodes

- name: Add rook-ceph labels to storage nodes
  hosts: storage
  become: yes
  vars:
    kubernetes_labels:
      - rook-ceph-node='true'
      - node-role.kubernetes.io/storage=''
  gather_facts: no
  roles:
    - label-nodes
