---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production-ips
  namespace: metallb-system
spec:
  addresses:
  - 10.10.199.20-10.10.199.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: production-ips
  namespace: metallb-system
spec:
  ipAddressPools:
  - production-ips
