---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production-ips
  namespace: metallb-system
spec:
  addresses:
  - 10.10.199.21-10.10.199.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: production-ips
  namespace: metallb-system
spec:
  ipAddressPools:
  - production-ips
  nodeSelectors:
    - matchLabels:
        lootbot.cloud/node-interfaces: "k8s-vip"
  interfaces:
    - k8s-vip
