---
- name: Check if containerd is installed
  command: which containerd
  register: containerd_installed
  ignore_errors: true

- name: Check if containerd service is running
  systemd:
    name: containerd
    state: started
  register: containerd_service
  ignore_errors: true
  when: containerd_installed.rc == 0

- name: Debug containerd installation status
  debug:
    msg: "Containerd is already installed and running."
  when: containerd_installed.rc == 0 and containerd_service.status.ActiveState == 'active'

- name: Include containerd install tasks
  include_tasks: containerd.yml
  when: containerd_installed.rc != 0 or containerd_service.status.ActiveState != 'active'
