---
- name: Check if the node is already part of the cluster
  command: "kubectl get node $(hostname -s) --kubeconfig=/etc/kubernetes/kubelet.conf"
  register: node_check
  ignore_errors: true
  changed_when: false

- name: Ensure the kubeadm join command is executed
  shell: "kubeadm join {{ hostvars['control-plane-01']['control_plane_endpoint'] }} --token {{ hostvars['control-plane-01']['token'] }} --discovery-token-ca-cert-hash {{ hostvars['control-plane-01']['discovery_token_ca_cert_hash'] }}"
  when: node_check.failed
  register: join_result
  ignore_errors: true

- name: Debug the join command output
  debug:
    msg: "{{ join_result.stdout }}"
  when: node_check.failed

- name: Rejoin the node if it's not part of the cluster
  shell: "kubeadm reset -f && kubeadm join {{ hostvars['control-plane-01']['control_plane_endpoint'] }} --token {{ hostvars['control-plane-01']['token'] }} --discovery-token-ca-cert-hash {{ hostvars['control-plane-01']['discovery_token_ca_cert_hash'] }}"
  when: node_check.failed and join_result.failed
  ignore_errors: true
